### ISSUE TITLE
Alert "Data Science Pipelines Application Route Error Burn Rate" fires when a DataSciencePipelineApplication is created

### ISSUE THREAD

**Issue by HumairAK** [red-hat-data-services/data-science-pipelines-operator#42]
Initially reported by: @jgarciao 

Description of problem:

In RHODS 1.26, when a new DataSciencePipelineApplication is created, alert Data Science Pipelines Application Route Error Burn Rate fires. It's possible the reason is because the pipeline services are created before the pods are Running.

This alert's severity is "info" (won't page SRE), so leaving the bug with normal priority
Prerequisites (if any, like setup, operators/versions):

 
Steps to Reproduce

    Create Project
    Verify alert Data Science Pipelines Application Route Error Burn Rate is not firing
    Connect to RHODS Dashboard
    Create Data Science Project
    Click on "Create Pipeline Server" (included in RHODS Dashboard 1.27, what is doing is to create a DataSciencePipelineApplication)
    Wait a few minutes
    Verify alert Data Science Pipelines Application Route Error Burn Rate is firing

Actual results:

Alert is firing
Expected results:

Alert should not fire when creating a pipeline
Reproducibility (Always/Intermittent/Only Once):

Always
Build Details:

I've tested this using RHODS 1.26 + WIP RHODS Dashboard for 1.27

**Comment by DharmitD** [comment]
https://github.com/red-hat-data-services/data-science-pipelines-operator/assets/46318816/f82de05b-d116-47af-a573-1b5f33791635

Replicated these exact steps in 1.27, the alert doesn't seem to be firing, pods and services come up instantly and correctly too

**Comment by DharmitD** [comment]
Replicated these exact steps in 1.28 as well, the alert doesn't seem to be firing, pods and services come up instantly and correctly too.

**Comment by DharmitD** [comment]
Closing since this has been tested by both us and QE, and the alerts don't go to pending or firing state.

cc: @jgarciao
